task: detection

num_classes: 28
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/det/public/train/images/
    ann_file: /data/det/public/train/public_groundtruth.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 16
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/det/warmup/train/images
    ann_file: /data/det/warmup/train/warmup_groundtruth.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 16
  drop_last: False
